name: basearch
description: Flutter Sample Architecture Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0
  localization: ^2.1.0
  flutter_svg: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mask_text_input_formatter: ^2.1.0
  dio: ^4.0.6
  email_validator: "0.1.4"
  get: "4.6.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8

flutter:

  uses-material-design: true
  
  assets:
    - lib/assets/i18n/
    - lib/assets/icons/
    - lib/assets/images/

  fonts:
    - family: Fredoka One
      fonts:
        - asset: lib/assets/fonts/FredokaOne-Regular.ttf

    - family: Kanit
      fonts:
        - asset: lib/assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Kanit-Black.ttf
          weight: 400
        - asset: lib/assets/fonts/Kanit-BlackItalic.ttf
          weight: 400
          style: italic
  
    - family: Ubuntu
      fonts:
        - asset: lib/assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Ubuntu-Regular.ttf
          weight: 500
        - asset: lib/assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic


